#!/usr/bin/env python3
"""Render the full per-cell head-to-head matrix as markdown, from the receipts.

Exists so the table in RESULTS-unsloth-head-to-head.md is DERIVED rather than
retyped. Every figure in this repo that was ever retyped by hand acquired an
error eventually; the reducers are mechanical for the same reason.

    python bench/phase1/render_h2h_matrix.py > matrix.md

Ratios are time relative to the fused kernel:
  u/f      >1 == fused faster (4-bit storage, dequant charged to unsloth)
  bf16/f   <1 == unsloth faster (bf16-resident: their design point)
  J/tok    >1 == fused more energy-efficient
  proxy    tgale96's grouped_gemm.ops.gmm over unsloth's real kernel
"""
from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
RES = HERE / "results" / "unsloth_h2h"
# The two CONFIRMED devices. Runs 1 and 3 are superseded (run 1 was never
# paired; run 3's second device was an A5000 and its training arms were unfair).
DEVICES = [("H100", RES / "run2" / "H100"), ("4090", RES / "run4" / "ADA3")]
REGIMES = ["decode_bs1", "decode_m8", "prefill_s2048"]


def load(dirp: Path):
    """Per-cell ratios + energy, medians across the 3 fresh-process reps."""
    ratios, energy = {}, {}
    verdict = json.loads((dirp / "verdict.json").read_text())
    for key, row in verdict.get("table", {}).items():
        model, proj, regime = key.split("|")
        ratios[(model, proj, regime)] = {
            k: (row[k]["median"] if row.get(k) else None)
            for k in ("unsloth_native_vs_fused", "unsloth_bf16_vs_fused",
                      "proxy_vs_native")
        }
    per = {}
    for rep in sorted(dirp.glob("h2h_rep*.json")):
        cells = json.loads(rep.read_text()).get("cells", [])
        idx = {(c["model"], c["proj"], c["regime"], c["backend"]): c for c in cells}
        for (m, p, r, b), c in idx.items():
            if b != "unsloth_native":
                continue
            base = idx.get((m, p, r, "fused_nf4"))
            if c.get("j_per_token") and base and base.get("j_per_token"):
                per.setdefault((m, p, r), []).append(
                    c["j_per_token"] / base["j_per_token"])
    for k, v in per.items():
        energy[k] = statistics.median(v)
    return ratios, energy, verdict


def main() -> int:
    data = {}
    for name, d in DEVICES:
        if not (d / "verdict.json").exists():
            print(f"missing receipts: {d}", file=sys.stderr)
            return 2
        data[name] = load(d)

    keys = sorted({k for name in data for k in data[name][0]})
    out = []
    out.append("## Appendix — full per-cell matrix\n")
    out.append("Generated by `bench/phase1/render_h2h_matrix.py` from the committed "
               "receipts. Do not hand-edit; re-run it.\n")
    for name, d in DEVICES:
        v = data[name][2]
        fp = v.get("unsloth_native_env") or {}
        out.append(f"- **{name}** — {v.get('gpu')} (cc {v.get('capability')}), "
                   f"TMA `{fp.get('supports_tma') if isinstance(fp, dict) else '?'}`, "
                   f"n={v.get('n_reps')} reps, verdict **{v.get('VERDICT')}**")
    out.append("\n`u/f` and `J/tok`: **>1 = gnf4 faster / more efficient**. "
               "`bf16/f`: **<1 = Unsloth faster** (their bf16-resident design point, "
               "where gnf4 does not compete). `proxy`: tgale96's package over "
               "Unsloth's real kernel.\n")

    for regime in REGIMES:
        out.append(f"\n### `{regime}`\n")
        out.append("| shape | proj | H100 u/f | H100 bf16/f | H100 J/tok | "
                   "4090 u/f | 4090 bf16/f | 4090 J/tok | proxy (H100) |")
        out.append("|---|---|---:|---:|---:|---:|---:|---:|---:|")
        for k in [x for x in keys if x[2] == regime]:
            m, p, _ = k
            c = [f"| `{m.split('/')[-1]}` | {p} "]
            for name in ("H100", "4090"):
                r, e, _ = data[name]
                row = r.get(k, {})
                for f in ("unsloth_native_vs_fused", "unsloth_bf16_vs_fused"):
                    val = row.get(f)
                    c.append(f"| {val:.3f} " if val else "| – ")
                ej = e.get(k)
                c.append(f"| {ej:.2f} " if ej else "| – ")
            px = data["H100"][0].get(k, {}).get("proxy_vs_native")
            c.append(f"| {px:.3f} |" if px else "| – |")
            out.append("".join(c))

    # Per-regime medians: the M-axis reading, computed not asserted.
    out.append("\n### Median `u/f` by regime\n")
    out.append("| regime | H100 | 4090 |")
    out.append("|---|---:|---:|")
    for regime in REGIMES:
        row = [f"| `{regime}` "]
        for name in ("H100", "4090"):
            vals = [data[name][0][k]["unsloth_native_vs_fused"] for k in keys
                    if k[2] == regime and data[name][0].get(k, {}).get("unsloth_native_vs_fused")]
            row.append(f"| {statistics.median(vals):.2f} " if vals else "| – ")
        out.append("".join(row) + "|")

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
