#!/usr/bin/env python3
"""Build llms-full.txt -- a deterministic, curated context bundle for language
models and coding agents. A project-generated convenience, NOT part of the
llms.txt proposal; llms.txt (hand-written, at the repository root) is the
orientation file, this is the concatenation it points to.

Inputs are the curated list in docs/llms-bundle.json (README opening up to a
marker, SOLUTIONS index and pages, capabilities.json, STATUS, the named
architecture/API documents, and a projection of the ACTIVE claims). Excluded
by construction: the full CHANGELOG, raw receipts, binaries, .ots files,
telemetry, historical duplicates. No timestamps. Each source gets a boundary
heading with its canonical main-branch URL.

    python scripts/build_llms_bundle.py            # write llms-full.txt
    python scripts/build_llms_bundle.py --check    # exit 1 if stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

RETIRED = {"retired", "superseded", "withdrawn", "falsified"}


def _readme_opening(text: str, marker: str) -> str:
    i = text.find(marker)
    return text if i < 0 else text[:i].rstrip() + "\n"


def _claims_projection(claims_path: Path, keep_tiers: set[str]) -> str:
    d = json.loads(claims_path.read_text())
    claims = d["claims"] if isinstance(d, dict) and "claims" in d else d
    lines = ["Active claims (projection of docs/claims.json; the file is authoritative and carries evidence paths):", ""]
    n = 0
    for c in claims:
        st = str(c.get("status", "")).lower(); tier = str(c.get("tier", "")).lower()
        if st in RETIRED or tier in RETIRED or (keep_tiers and tier not in keep_tiers):
            continue
        n += 1
        lines.append(f"- {c['id']} [{c.get('tier', '?')}]: {c.get('claim', '').strip()}")
    lines.append("")
    lines.append(f"({n} active claims listed; retired and superseded claims are omitted on purpose.)")
    return "\n".join(lines) + "\n"


def build(root: Path, cfg: dict) -> str:
    base = cfg["canonical_url_base"].rstrip("/") + "/"
    out = [f"# {cfg['title']}", "", cfg["preamble"].strip(), "",
           "Generated by scripts/build_llms_bundle.py from the sources named in docs/llms-bundle.json.",
           "Each section below starts with `## Source:` and the canonical URL of the file it was taken from.", ""]
    for item in cfg["sources"]:
        kind = item.get("kind", "file")
        if item.get("glob"):
            parts = []
            for f in sorted(root.glob(item["glob"])):
                parts.append(f"## Source: {f.relative_to(root)} ({base}{f.relative_to(root)})\n\n{f.read_text(errors='replace').strip()}\n")
            out.append("\n".join(parts)); continue
        if kind == "claims":
            body = _claims_projection(root / item["path"], set(item.get("tiers", [])))
        else:
            p = root / item["path"]
            body = p.read_text(errors="replace")
            if item.get("until_marker"):
                body = _readme_opening(body, item["until_marker"])
        out.append(f"## Source: {item['path']} ({base}{item['path']})")
        out.append("")
        out.append(body.strip())
        out.append("")
    text = "\n".join(out).rstrip() + "\n"
    return text


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".")
    ap.add_argument("--config", default="docs/llms-bundle.json")
    ap.add_argument("--out", default="llms-full.txt")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    root = Path(a.root).resolve()
    cfg = json.loads((root / a.config).read_text())
    text = build(root, cfg)
    outp = root / a.out
    limit = cfg.get("max_bytes", 400_000)
    if len(text.encode()) > limit:
        print(f"FAIL: bundle is {len(text.encode())} bytes > max_bytes {limit}; trim docs/llms-bundle.json"); return 1
    if a.check:
        if not outp.exists() or outp.read_text() != text:
            print(f"FAIL: {a.out} is stale -- run: python scripts/build_llms_bundle.py"); return 1
        print(f"OK: {a.out} is current ({len(text.encode())} bytes, {len(cfg['sources'])} sources)"); return 0
    outp.write_text(text)
    print(f"wrote {a.out} ({len(text.encode())} bytes, {len(cfg['sources'])} sources)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
