#!/usr/bin/env python3
"""Build llms-full.txt -- a deterministic, curated context bundle for language
models and coding agents. A project-generated convenience, NOT part of the
llms.txt proposal; llms.txt (hand-written, at the repository root) is the
orientation file, this is the concatenation it points to.

Inputs are the curated list in docs/llms-bundle.json (README opening up to a
marker, SOLUTIONS index and pages, capabilities.json, STATUS, the named
architecture/API documents, and a projection of docs/claims.json). Excluded
by construction: the full CHANGELOG, raw receipts, binaries, .ots files,
telemetry, historical duplicates. No timestamps. Each source gets a boundary
heading with its canonical main-branch URL; a ``glob`` source becomes one
section per matching file.

The claims projection lists every claim with an ACTIVE status under its own
``[status]`` (measured-private ones flagged "receipt private"), then ``open``
claims under "Open items" and ``projected`` ones under "Projections";
retired and superseded claims are omitted on purpose. A README
``until_marker`` that is not found is a failure, not the whole file.

    python scripts/build_llms_bundle.py            # write llms-full.txt
    python scripts/build_llms_bundle.py --check    # exit 1 if stale
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from discovery_common import ACTIVE_STATUSES, ContractError, bundle_sources, load_claims, read_text, write_text  # noqa: E402


def _readme_opening(text: str, marker: str, path: str) -> str:
    i = text.find(marker)
    if i < 0:
        raise ContractError(f"{path}: until_marker {marker!r} not found -- the opening would silently become the whole file")
    return text[:i].rstrip() + "\n"


def _claims_projection(root: Path, claims_path: str) -> str:
    claims, _vocab = load_claims(root, claims_path)

    def line(c: dict) -> str:
        st = c["status"]
        flag = " (receipt private)" if st == "measured-private" else ""
        return f"- {c['id']} [{st}]{flag}: {c.get('claim', '').strip()}"

    active = [c for c in claims if c["status"] in ACTIVE_STATUSES]
    open_items = [c for c in claims if c["status"] == "open"]
    projected = [c for c in claims if c["status"] == "projected"]
    lines = ["Active claims (projection of docs/claims.json; the file is authoritative and carries evidence paths):", ""]
    lines += [line(c) for c in active]
    if open_items:
        lines += ["", "Open items (no evidence either way):", ""]
        lines += [line(c) for c in open_items]
    if projected:
        lines += ["", "Projections (arithmetic, not runs):", ""]
        lines += [line(c) for c in projected]
    lines.append("")
    lines.append(f"({len(active)} active claims listed, {len(open_items)} open, {len(projected)} projected; "
                 "retired and superseded claims are omitted on purpose.)")
    return "\n".join(lines) + "\n"


def build(root: Path, cfg: dict) -> str:
    base = cfg["canonical_url_base"].rstrip("/") + "/"
    out = [f"# {cfg['title']}", "", cfg["preamble"].strip(), "",
           "Generated by scripts/build_llms_bundle.py from the sources named in docs/llms-bundle.json.",
           "Each section below starts with `## Source:` and the canonical URL of the file it was taken from.", ""]
    for item in bundle_sources(root, cfg):
        if item.get("kind", "file") == "claims":
            body = _claims_projection(root, item["path"])
        else:
            body = read_text(root / item["path"])
            if item.get("until_marker"):
                body = _readme_opening(body, item["until_marker"], item["path"])
        out.append(f"## Source: {item['path']} ({base}{item['path']})")
        out.append("")
        out.append(body.strip())
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".")
    ap.add_argument("--config", default="docs/llms-bundle.json")
    ap.add_argument("--out", default="llms-full.txt")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    root = Path(a.root).resolve()
    cfg = json.loads(read_text(root / a.config))
    try:
        text = build(root, cfg)
    except ContractError as e:
        print(f"FAIL: {e}")
        return 1
    outp = root / a.out
    limit = cfg.get("max_bytes", 400_000)
    n_bytes = len(text.encode("utf-8"))
    if n_bytes > limit:
        print(f"FAIL: bundle is {n_bytes} bytes > max_bytes {limit}; trim docs/llms-bundle.json")
        return 1
    if a.check:
        if not outp.exists() or read_text(outp) != text:
            print(f"FAIL: {a.out} is stale -- run: python scripts/build_llms_bundle.py")
            return 1
        print(f"OK: {a.out} is current ({n_bytes} bytes, {len(cfg['sources'])} sources)")
        return 0
    write_text(outp, text)
    print(f"wrote {a.out} ({n_bytes} bytes, {len(cfg['sources'])} sources)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
